Feature/add GitHub actions
PyAr/asoc_members pull request #207
Opened 2021-05-22 23:34 UTC by lecovi

2021-05-23 01:45 UTC, tzulberti commented
Buenas. Porque usar Github Actions en vez de travis? Justo cree un ticket el otro dia para que todos los repos usen los mismo (https://github.com/PyAr/pyar_infra/issues/81), y me interesaria saber porque cambiar uno por el otro.

Por el otro lado, creo que el PR de bumpear la version de Django debería ser la base para este PR porque figuran muchos cambios de ese PR

2021-05-23 22:20 UTC, facundobatista commented
> Buenas. Porque usar Github Actions en vez de travis? 

Travis entró en una fase de migración de organización pública a comercial o algo parecido.

La otra vez estuve peleando un montón con dónde están los repos de PyAr, si travis.com o travis.org, y no los podía hacer andar, el final fue feliz ahí pero fue un laburo.

Este cambio acá está originado porque Leandro metió un PR, y yo me di cuenta que Travis, UNA VEZ MÁS, no contestaba. Me pareció bien ir a GA.

Leandro después investigó, y encontró que parece que se nos acabó el crédito en Travis (?!), [adjunto screenshot](https://user-images.githubusercontent.com/184060/119278457-d0406a80-bbfb-11eb-84d3-5475b30fb78e.png).

Más allá de eso, sí, en este PR está todo mezclado.

2021-05-23 22:21 UTC, facundobatista requested changes
Quedó todo mezclado en este PR, hay que separar lo de GA solito... Gracias!

2021-05-25 15:31 UTC, lecovi commented
Si, este PR quedó mezclado porque quería ver GA y creé un branch a partir de mi PR, no me di cuenta que tendría que haberlo hecho a partir de master.
BTW, mi PR #206 está basado a partir del #203 así que podríamos jugar con ese #203.

Cierro esto para con genera más ruido.

2021-05-25 15:31 UTC, closed without merging